### ISSUE TITLE
Sync dbt issues with superset-cli commands

### ISSUE THREAD

**Issue by yinkaihsu** [preset-io/backend-sdk#101]
Hi @betodealmeida , 

I have tried sync dbt command with database / dataset on Superset, with the following syntax:
```
superset-cli -u USER_NAME -p USER_PASS SUPERSET_URL sync dbt-core PATH/TO/manifest.json --project PROJECT_NAME --profiles PATH/TO/profiles.yml --exposures PATH/TO/exposures.yaml --import-db,
```

There are two issues I encounter currently: 

- **After successfully creating datasets from `dbt models` (no error messages appears), datasets are not shown in Superset.**

Sample log info:
```
[15:34:30] INFO     [[15:34:30]] INFO: preset_cli.cli.superset.sync.dbt.datasets: Creating dataset model.jaffle_shop.my_first_dbt_model                                                      datasets.py:84
           INFO     [[15:34:30]] INFO: preset_cli.cli.superset.sync.dbt.datasets: Creating dataset model.jaffle_shop.my_second_dbt_model                                                     datasets.py:84
```
Still figuring out why dataset doesn't show up...

- **It fails when there is already DB connection of BQ.**

Error could come from here: 
https://github.com/preset-io/backend-sdk/blob/9faec57f34ff4410145203566641637720a0879c/src/preset_cli/cli/superset/sync/dbt/databases.py#L61

Changing `connection_params.get("encrypted_extra")` to `connection_params.get("masked_encrypted_extra")` should fix this issue.

**Comment by betodealmeida** [comment]
> About the following issue:
> 
>     * **After successfully creating datasets from dbt models (no error messages appears), datasets are not shown in Superset.**
> 
> 
> https://github.com/preset-io/backend-sdk/blob/9faec57f34ff4410145203566641637720a0879c/src/preset_cli/cli/superset/sync/dbt/datasets.py#L35
> 
> it seems like `sqlalchemy` package `make_url` won't get the exact database name by calling `url.database` when using BQ connections.

Ah, I think this is a quick fix, let me work on it.

**Comment by yinkaihsu** [comment]
@betodealmeida 

> About the following issue:
> 
> * **After successfully creating datasets from dbt models (no error messages appears), datasets are not shown in Superset.**
> 
> https://github.com/preset-io/backend-sdk/blob/9faec57f34ff4410145203566641637720a0879c/src/preset_cli/cli/superset/sync/dbt/datasets.py#L35
> 
> it seems like `sqlalchemy` package `make_url` won't get the exact database name by calling `url.database` when using BQ connections.

This bug is fixed, thanks a lot!

The issue with dbt sync database also needs to change a bit:

> * **It fails when there is already DB connection of BQ.**
> 
> Error could come from here:
> 
> https://github.com/preset-io/backend-sdk/blob/9faec57f34ff4410145203566641637720a0879c/src/preset_cli/cli/superset/sync/dbt/databases.py#L61
> 
> Changing `connection_params.get("encrypted_extra")` to `connection_params.get("masked_encrypted_extra")` should fix this issue.

**Comment by betodealmeida** [comment]
This should be fixed in https://github.com/preset-io/backend-sdk/pull/111/.
