### ISSUE TITLE
Discussion: DBT Metrics Label vs Name

### ISSUE THREAD

**Issue by cwegener** [preset-io/backend-sdk#103]
Hi Beto,

First off, big kudos to you for the last three weeks work on this project. I hadn't been paying attention to the project  in the last three weeks and was just catching up with all the updates. This is really quickly turning into an indispensable tool for me!

Question:

I was wondering about the choice of using the the DBT metric 'name' field as the  value for the Metric Label in Superset instead of using the DBT metric's 'label' field value.

Is there a specific reason for that? At first glance through the preset-cli codebase I couldn't spot if this is something that's even happening in the preset-cli codebase, or if this might just be a bug in the Superset API?

**Comment by betodealmeida** [comment]
Thanks, @cwegener!

That was just an oversight, we should definitely use the label. Let me fix it.
