### ISSUE TITLE
DBT Sync: Creating new Dataset fails after #95

### ISSUE THREAD

**Issue by cwegener** [preset-io/backend-sdk#104]
On Postgres, creating new datasets from `superset-cli sync dbt` quietly fails. No error message is displayed either in `superset-cli` or `superset`.
Datasets are just not created.

**Comment by betodealmeida** [comment]
@cwegener can you test with the latest `main`? I think https://github.com/preset-io/backend-sdk/pull/111/ should fix it.

**Comment by cwegener** [comment]
Thanks. Just updated to latest `main` and the issue is now fixed.
