### ISSUE TITLE
Syncing to different Snowflake databases produces an error

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#113]
When syncing models that are in different databases, I get the following error:

```
[[09:32:48]] ERROR: preset_cli.cli.superset.sync.dbt.datasets: Unable to create dataset                                                                                                           datasets.py:99
                    Traceback (most recent call last):                                                                                                                                                                              
                      File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/datasets.py", line 97, in sync_datasets                                                                                         
                        dataset = create_dataset(client, database, model)                                                                                                                                                           
                      File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/datasets.py", line 63, in create_dataset                                                                                        
                        return client.create_dataset(**kwargs)                                                                                                                                                                      
                      File "/usr/local/lib/python3.9/site-packages/preset_cli/api/clients/superset.py", line 534, in create_dataset                                                                                                 
                        elif column["type"].lower() == "string":                                                                                                                                                                    
                    AttributeError: 'NoneType' object has no attribute 'lower'                                  
```

The models in the same database sync OK.  

I'm wondering if the fact that we have [Snowflake](https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup), and that the `profiles.yml` file requires a `database` key, is throwing things off?

For example, on BigQuery, the `profiles.yml` file does not require a `database` to be defined.  But in Snowflake, you must have this defined.  However, you can override this database in the `dbt_project.yml` file.

It seems like the preset-cli is using the database from the `profiles.yml` file and not what's defined in the `dbt_project.yml` file.  

Setup is as follows:
OS: MacOS 12.6
dbt version: 1.2.1
preset-cli version: 0.1.1.post1.dev74+g77b5cfd

**Comment by dweaver33** [comment]
Related to #73

**Comment by betodealmeida** [comment]
> For example, on BigQuery, the `profiles.yml` file does not require a `database` to be defined. But in Snowflake, you must have this defined. However, you can override this database in the `dbt_project.yml` file.

Ah, I wasn't aware. Right now the CLI is not reading `dbt_project.yml` at all, I think it might be better to pass it as an option instead of the project name and the manifest (since it contains the first and allows us to infer the second).

Do you have an example of how you override `database` in `dbt_project.yml`?

**Comment by betodealmeida** [comment]
Something like this?

https://github.com/dbt-msft/dbt-sqlserver/issues/59#issue-743136222

**Comment by dweaver33** [comment]
> Something like this?
> 
> https://docs.getdbt.com/reference/model-configs#general-configurations

That's correct.

**Comment by betodealmeida** [comment]
Thanks, @dweaver33, I'm working on it.

**Comment by betodealmeida** [comment]
It's weird, though... I tested and the overrides are reflected in the `manifest.json` (as it should), so I don't think this is the problem.

i think what's going on is that for models in different databases the CLI is creating a _virtual_ dataset in Superset, and because of that we don't know the column information.

**Comment by betodealmeida** [comment]
I have a tentative fix in https://github.com/preset-io/backend-sdk/pull/116.
