### ISSUE TITLE
Support dbt-core 1.3

### ISSUE THREAD

**Issue by cwegener** [preset-io/backend-sdk#126]
dbt-core 1.3 changes the metric spec as follows:

- `type` --> `calculation_method`
- `sql` --> `expression`
- `type: expression` --> `calculation_method: derived`

`superset-cli` should:

1. Either know which version of dbt-core is used and use the correct marshmallow MetricSchema version depending on version number
2. Or dynamically infer the MetricSchema during runtime (with `Schema.from_dict`)

From looking at dbt-cloud API, there seems to be know way to dynamically detect the dbt-core version of a particular dbt-cloud environment.

**Comment by betodealmeida** [comment]
Ah, thanks @cwegener! I'll fix this!

**Comment by cwegener** [comment]
I'm sure there are likely more options of how to do this in marshmallow. Actually on second thought, dynamically inferring the schema alone is not sufficient to deal with this.

**Comment by PaxonF** [comment]
Any chance support for dbt-core 1.3 will be added soon? I'm looking to sync metrics to Preset, but I do run into some key errors when trying to create a metric with `calculation_method: average`.

`File "/Users/paxonfischer/Documents/GitHub/dbt/.venv/lib/python3.8/site-packages/preset_cli/cli/superset/sync/dbt/metrics.py", line 35, in get_metric_expression
    type_ = metric["type"]`

**Comment by cwegener** [comment]
Same issue here. Just doing my testing of #154 and I do get the `KeyError` as well.

**Comment by betodealmeida** [comment]
This should be fixed in #159.
