### ISSUE TITLE
Ability to sync only exposures from dbt, without syncing models

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#130]
Users would like to be able to sync all exposures, but not all models from dbt to Preset. So, rather than determining which models exist in Preset, selecting those models, and syncing and showing exposures for those models, they would like to skip the first two steps and just show exposures.

**Comment by betodealmeida** [comment]
Implemented in #132. To run it without syncing models is a bit weird, though:

```bash
$ preset-cli superset sync dbt-core ... --exposures=... --select tag:bogus
```

Where "bogus" is a tag that no model has.
