### ISSUE TITLE
The import-db flag is not functioning as expected

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#168]
### Current Problem:
If you run a dbt sync with the preset-cli, regardless of setting the `--import-db` flag, if a database is found in Preset, it will overwrite the connect.  The problem is that the database user used during sync may not be the same user that will be used in Preset.  

## Solution:
Make it so if the `--import-db` setting is not present, skip overwriting the database connection.

**Comment by Vitor-Avila** [comment]
Fixed in https://github.com/preset-io/backend-sdk/pull/193
