### ISSUE TITLE
Allow selection of dbt models based on file name

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#171]
Currently the `preset-cli` allows selection of dbt models using the graph selectors and tags.  However, it would be nice to also allow the use of the model file names as well.  

Example would be:
```bash
preset-cli ... --select models/datamarts/my_model.sql                                                  #sync only "my_model"
preset-cli ... --select models/datamarts/my_model.sql  --select models/datamarts/my_other_model.sql    #sync "my_model" and "my_other_model"
```

**Comment by dweaver33** [comment]
@Vitor-Avila, any update if we can get this?  Without this, our CI/CD deployments are becoming very time consuming as we have to deploy all the models.

**Comment by Vitor-Avila** [comment]
hey @dweaver33, I've performed a few tests on my end, and I can use `--select` with the actual model names. Are you looking to use the file name instead to use the terminal auto-complete functionality? Also, are you looking to use a folder to include subfiles (https://github.com/preset-io/backend-sdk/issues/217)?

**Comment by dweaver33** [comment]
> hey @dweaver33, I've performed a few tests on my end, and I can use `--select` with the actual model names. Are you looking to use the file name instead to use the terminal auto-complete functionality? Also, are you looking to use a folder to include subfiles (https://github.com/preset-io/backend-sdk/issues/217)?

Yes, I'd like to use the full file name and path as a selection option. A folder option would be nice as well, but it a specific need I have. 

My use case is that we have a process that detects which files have changed. This process outputs the full file names of all files that changes (with a separator). I'd like to feed this output to the Preset CLI so I could selectively deploy models to Preset.

**Comment by Vitor-Avila** [comment]
ok, thanks for sharing more context -- this is really helpful. I'm finishing working on two other CLI issues, and then I can take a look at this.

**Comment by Vitor-Avila** [comment]
@dweaver33 I have a potential implementation for this here: https://github.com/preset-io/backend-sdk/pull/242
