### ISSUE TITLE
Exposure names contain invalid characters

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#177]
Currently when sync'ing with dbt, the exposures from Preset use the `name` property to pull the name of the exposure.  This causes problems as the name defined in Preset can contain invalid characters for dbt exposure names.  Per [documentation here](https://docs.getdbt.com/reference/exposure-properties), exposure names can only contain letters, numbers, and underscores (no spaces or special characters)

I propose we change the behavior to take the Preset name, cleanse it to contain only letters, numbers, and underscores (no spaces or special characters) and use this for the `name` property. 

Then we can use the original Preset name in the `label` property.

**Comment by Vitor-Avila** [comment]
Hey @dweaver33, 

Sorry for the delay here. I'm working on this issue this week, and should have a PR soon.

**Comment by dweaver33** [comment]
Thank you!

**Comment by Vitor-Avila** [comment]
I have a potential fix here: https://github.com/preset-io/backend-sdk/pull/221

**Comment by dweaver33** [comment]
Thank you!  We'll do some testing and let you know.
