### ISSUE TITLE
Calling superset assets api with JWT token fails because no csrf token is used

### ISSUE THREAD

**Issue by royxact** [preset-io/backend-sdk#183]
Trying to use backend sdk with a superset instance using the jwt authentication. The action is import. 
Problem is, call to assets api fails since it's a POST call but it's not sending a csrf token. 
Could be useful to fix that.
Thanks,
Roy

**Comment by Vitor-Avila** [comment]
Hey @royxact, 

Would you mind sharing the Superset version you are running? Just so that we can reproduce it on our end.

Thank you!

**Comment by royxact** [comment]
Sure, it's 2.0.1
