### ISSUE TITLE
Ability to sync models from dbt without certifying the datasets

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#209]
### Current Scenario
When syncing dbt models to Preset, the corresponding datasets are created and automatically certified.

### Suggested Improvement
Provide the ability to specify the datasets that should be certified, and also specify custom certification info.

**Comment by AntonAiven** [comment]
This is really an essential feature! We want to e.g. use dbts meta tag to define different stages for datamodels, and corresponding stages would then leave the datasets either uncertified, certified or get a warning (e.g. in case of a deprecated dataset)
