### ISSUE TITLE
dbt sync of redshift instance gives postgres backend for superset database

### ISSUE THREAD

**Issue by noppaz** [preset-io/backend-sdk#25]
When syncing a project where the target is of type redshift the db ending up in the superset instance is still of postgres backend type. I'd imagine this could cause problems further down the line, or at least be confusing to admins.

**Comment by betodealmeida** [comment]
Ah, good point, let me fix this.

**Comment by betodealmeida** [comment]
For reference, we should use https://superset.apache.org/docs/databases/redshift/.
