### ISSUE TITLE
Is this project active and alive?

### ISSUE THREAD

**Issue by skwaugh** [preset-io/backend-sdk#28]
Hi.  Was very excited to find this project via the conversation here  #https://github.com/apache/superset/pull/18098
Is this a WIP and/or being kept under wraps for now?  

I know people in the dbt slack community are still using dbt-superset-lineage, which can do about 10% of what is described in this project's README.

Is `backend-sdk` stable enough to use for internal projects today?

**Comment by betodealmeida** [comment]
Hi, @skwaugh! It is still alive, and we started using it in production at Preset. Feel free to file bug tickets if you have any problems using it!
