### ISSUE TITLE
Syncing new dataset results in error report despite success

### ISSUE THREAD

**Issue by adamcunnington-mlg** [preset-io/backend-sdk#317]
We've noticed that deploying a new dataset always spits out an error despite the fact that i) it succeeds as far as Preset UI is concerned and ii) reports success even though we're using --raise-failures (which might be a distinct issue or it might be that the error handling is correctly realising that this isn't an error whilst also spitting out error erroneously!)

![image](https://github.com/user-attachments/assets/6c192e8b-be10-426b-b48d-04d48d0c05b5)
![image](https://github.com/user-attachments/assets/7d30e345-eddd-4bae-83ad-e8440cc2b91f)

If I'm not misremembering (quite possible), at one stage, we had similar issue when the syncing of columns of existing dataset encountered a STRUCT/RECORD but I think that was fixed and that isn't relevant here because this dataset is actually very simple and only comprises basic column types / simple metrics.

This is on 0.2.18 which I'm aware isn't the most current version but it's fairly recent and I don't think there are any fixes related to this since then.

If I run the sync again, it succeeds - so defo feels like some situational bug on new datasets only (or maybe that's red herring - perhaps it's to do with certain metadata getting skipped due to `--preserve-metadata` flag, who knows - but the dataset appears successfully synced as far as Preset UI appears).

Here's a better example with me running same command twice in a row (first time it picks up a new dataset) with better IDE highlighting:
![image](https://github.com/user-attachments/assets/19751c17-f462-42bc-a916-3c018421329e)

**Comment by Vitor-Avila** [comment]
Hey @adamcunnington-mlg,

We're working to add support for catalogs in Preset, which should be added to an official Superset release as well as part of `4.1`. However, some users are already using catalogs when running Superset off of `master`, or a few selected Preset customers trialing the feature.

The CLI is already handling catalogs, so by default it tries to create a new dataset with the catalog information set. If it fails, it defaults to re-attempting the operation without the catalog information. That said, the `ERROR` message is indicating the API call failed (which did) but the sync itself doesn't face any issues as the dataset is created via fallback logic. You should no longer see this error once catalogs is fully deployed to Preset (soon!)

Let me know if you have any questions!

**Comment by adamcunnington-mlg** [comment]
Great, thanks for confirming - we'll ignore for now, cheers
