### ISSUE TITLE
Can i use preset-cli to async my data from dbt-core to my own apache superset?

### ISSUE THREAD

**Issue by andrewcaoo** [preset-io/backend-sdk#324]
I installed preset-cli follow by docs. 
When i run this command to async data to my Superset. 
`preset-cli --workspaces=http://localhost:8088 superset sync dbt-core ./target/manifest.json  --project=dbt_semantic_layer_demo --target=wh_demo --profiles=./profiles.yml`

It throw this error:
```
http://localhost:8088
[16:52:07] ERROR    [[16:52:07]] ERROR: preset_cli.lib: {                                                                                               lib.py:100
                        "msg": "The specified alg value is not allowed"
                    }
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
```
  
  Now, i can't identify any reasons. I make sure all the argumens are true.

**Comment by Vitor-Avila** [comment]
Hi @andrewcaoo,

For operations against a Superset instance (as opposed to a Preset Workspace), you can use `superset-cli` command. Please refer to our external docs: https://docs.preset.io/docs/the-preset-cli
