### ISSUE TITLE
Ability to export specific resources from a Workspace using the preset-cli

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#45]
### Motivation
Currently, it's possible to use the `preset-cli` to export all assets from a Workspace. However, in some cases users might just want to export modified assets, or specific ones.

The CLI only supports exporting all assets from the source Workspace.

### Proposed solution
Implement the ability to specify which assets should be exported. A possible solution would be to specify the `IDs` to be exported.

**Comment by betodealmeida** [comment]
Closed this by mistake.

**Comment by betodealmeida** [comment]
https://github.com/preset-io/backend-sdk/pull/84 allows specifying asset type
