### ISSUE TITLE
Handle Ownership re-mapping on Migrations

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#50]
## Description
The CLI can be a very powerful tool to migrate from Superset (on prem) to Preset. However, the current export flow doesn't include ownership data on the ZIP file, so as a result when the files are imported on the destination, everything gets mapped to the user that's performing the operation. 

## Suggested Solution
Implement to the CLI the ability to automatically re-map the content on the destination, based on the user info.

**Comment by betodealmeida** [comment]
Done.
