### ISSUE TITLE
Handle authentication (JWT generation) when interacting with Superset (local)

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#51]
## Description
Currently, the `superset-cli` allows users to interact with a Superset local installation. However, it gets the `csrf_token` from the login HTML content, and then work on getting a session/cookie to perform future requests.

## Suggested Improvement
Implement support to handling the authentication directly through the API:
* Sending a `POST` request to `/api/v1/security/login`; and/or
* Accept a `--jwt-token` parameter to be specified on the command.

**Comment by betodealmeida** [comment]
implemented in https://github.com/preset-io/backend-sdk/pull/82.
