### ISSUE TITLE
Syncing dbt model that is in different database than defined in profiles.yml file

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#73]
It seems this is because our staging tables are located in a different database than the default defined in the `profiles.yml` file for dbt. 

The command I'm running is this (removed company sensitive info):
```
preset-cli --workspaces=https://[REMOVED].app.preset.io/ superset sync dbt-core target/manifest.json --project=[REMOVED] --target=dev --import-db --disallow-edits --external-url-prefix=[REMOVED] --exposures=models/exposures.yml --select [REMOVED] 
```

When ran, we get the following result:
```
[09:03:49] INFO     [[09:03:49]] INFO: preset_cli.cli.superset.sync.dbt.databases: Found an existing database, updating it                                databases.py:54
[09:03:52] INFO     [[09:03:52]] INFO: preset_cli.cli.superset.sync.dbt.datasets: Creating dataset model.[REMOVED].[REMOVED]                     datasets.py:50
[09:03:57] ERROR    [[09:03:57]] ERROR: preset_cli.lib: {"message":"Fatal error"}   
```
Desired result:  Create a new connection for the staging tables to point to the correct database.

**Comment by dweaver33** [comment]
Updated with comments

**Comment by betodealmeida** [comment]
I'm a bit confused, I thought dbt projects could have [only one database](https://docs.getdbt.com/docs/faqs/connecting-to-two-dbs-not-allowed). @dweaver33 are these staging tables connected to the DAG of the project specified in the CLI? Or are they in a different project?

**Comment by dweaver33** [comment]
Same project and at least with Snowflake, you can have multiple databases. In fact, it's the most common way to segregate data on Snowflake.

**Comment by betodealmeida** [comment]
I see. The term "database" is very overloaded!

This one is tricky, because to add a dataset in Superset the database must also exist, so you'd need one Superset database for each database in Snowflake. Though in SQL Lab you can query across Snowflake databases with a single Superset database connection, as expected.
