### ISSUE TITLE
Sync dbt with bigquery failed using gcp service account

### ISSUE THREAD

**Issue by yinkaihsu** [preset-io/backend-sdk#93]
When I tried to sync dbt models on BigQuery to superset instance with the following command:  
```superset-cli -u USER_NAME -p USER_PASS SUPERSET_URL sync dbt-core PATH/TO/manifest.json --project PROJECT_NAME --profiles PATH/TO/profiles.yml --exposures PATH/TO/exposures.yaml --import-db```, 
it returned error message of `{"message":"Connection failed, please check your connection settings"}`.

However, it works well when using every `dbt` commands in the same project.

**Comment by betodealmeida** [comment]
@yinkaihsu what version are you using? Would you mind updating from the `main` branch and trying again? I fixed a bug recently in https://github.com/preset-io/backend-sdk/pull/71 that could explain this error.

**Comment by yinkaihsu** [comment]
@betodealmeida 
I have updated my package from `main` branch and it still have the same issue.
Thus, I tried to use Superset API to create BigQuery database directly, and seems like the error is from here:
https://github.com/preset-io/backend-sdk/blob/91a3209a0b2b829c26e08553044c027add8dc8b6/src/preset_cli/cli/superset/sync/dbt/lib.py#L106

When I use Superset API with field `masked_encrypted_extra` will work, so maybe change `parameters["encrypted_extra"]` to `parameters["masked_encrypted_extra"]` could solve the issue.

**Comment by betodealmeida** [comment]
Ah, good catch! Let me fix it.

**Comment by betodealmeida** [comment]
Merged the fix! Thanks, @yinkaihsu!
